### ISSUE TITLE
Installing on Linux (openSuse 15.1)

### ISSUE THREAD

**Issue by kostgr** [lukasmonk/lucaschess#106]
I've tried to install Lucas Chess on my openSuse Leap 15.1 using the tutorial.

I've got following issues:
- apt-get has to be replace with zypper install
- python-Packages should be python2-Packages.
- python-pyaudio should be python2-PyAudio
- python-dev is not available
- apt-get install python-chess is not available (python-chess is not available) => I had to use pip2 install 'python-chess>=0.23.0,<0.24.0', because python-chess is not supported for python2 starting from 0.24.0.
- "pip install" should be "pip2 install"

I had to modify xcython_linux.sh "LCEngine2.so" should be "LCEngine4.so".

After all of that I cannot start LucasChess with following error:
> python2 Lucas.py 
Traceback (most recent call last):
  File "Lucas.py", line 47, in <module>
    import Code.Init
  File "./Code/Init.py", line 5, in <module>
    from Code import Procesador
  File "./Code/Procesador.py", line 6, in <module>
    from Code import AperturasStd
  File "./Code/AperturasStd.py", line 1, in <module>
    import LCEngine4 as LCEngine
ImportError: libirina.so: cannot open shared object file: No such file or directory

Even if the libirina.so are there:
> find . -name libirina.so
./Engines/Linux32/_tools/libirina.so
./Engines/Linux64/_tools/libirina.so
./LCEngine/libirina.so
./libirina.so

**Comment by kostgr** [comment]
> cd Linux
> ./xlinux.sh

has worked for me.
Possible it would be possible to extend comments for Linux openSuse...

Thanks a lot.
