### ISSUE TITLE
Linux Mageia: Error when executing xcython_linux.sh

### ISSUE THREAD

**Issue by rchastain** [lukasmonk/lucaschess#127]
Hello! I try to install the latest version of LucasChess (11.17) in Linux Mageia. I get an error when I execute xcython_linux.sh:
```
[roland@portable LCEngine]$ sh ./xcython_linux.sh
rm: impossible de supprimer 'LCEngine4.so': Aucun fichier ou dossier de ce type
Traceback (most recent call last):
  File "./setup.py", line 7, in <module>
    ext_modules = cythonize([Extension("LCEngine4", ["LCEngine4.pyx"], libraries=["irina"])])
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 967, in cythonize
    aliases=aliases)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 826, in create_extension_list
    kwds = deps.distutils_info(file, aliases, base).values
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 681, in distutils_info
    return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 691, in transitive_merge
    node, extract, merge, seen, {}, self.cimported_files)[0]
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 696, in transitive_merge_helper
    deps = extract(node)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 665, in distutils_info0
    externs = _make_relative(externs, basedir)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 72, in _make_relative
    for path in file_paths]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
x86_64
cp: impossible d'évaluer 'LCEngine4.so': Aucun fichier ou dossier de ce type
cp: impossible d'évaluer 'LCEngine4.so': Aucun fichier ou dossier de ce type
[roland@portable LCEngine]$ 
```

**Comment by xaizek** [comment]
You seem to have non-ASCII characters in the path where LucasChess is located and Python doesn't like it. Move it somewhere else, at least during the build process.

P.S. It's a good idea to post error output in English, usually can be done like this: `LC_ALL=C sh ./xcython_linux.sh`.

**Comment by rchastain** [comment]
> You seem to have non-ASCII characters in the path where LucasChess is located and Python doesn't like it. Move it somewhere else, at least during the build process.

Yes, it solves the problem. Thank you.
 
> P.S. It's a good idea to post error output in English, usually can be done like this: `LC_ALL=C sh ./xcython_linux.sh`.

Thank you. I didn't know that.

Now I have a problem related to Python Chess.

```
[roland@portable Linux]$ LC_ALL=C sh xlucas.sh
x86_64
Traceback (most recent call last):
  File "./Lucas.py", line 44, in <module>
    import Code.Init
  File "./Code/Init.py", line 5, in <module>
    from Code import Procesador
  File "./Code/Procesador.py", line 30, in <module>
    from Code import GestorRoutes
  File "./Code/GestorRoutes.py", line 11, in <module>
    from Code import LibChess
  File "./Code/LibChess.py", line 4, in <module>
    import chess
ImportError: No module named chess
[roland@portable Linux]$ 
```
I don't find it in Mageia packages. (I didn't use the command line to install packages, but the Mageia packages manager. The commands from the documentation don't work for me.)

**Comment by xaizek** [comment]
Use `pip install python-chess==v0.23.11` (or `pip install 'python-chess<0.24'`; both should yield the same result) either with `sudo` or add `--user` after `install`.

**Comment by rchastain** [comment]
Yes, it works but I still get the same error message.
```
[roland@portable Linux]$ sudo pip install python-chess==v0.23.11
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting python-chess==v0.23.11
  Downloading https://files.pythonhosted.org/packages/4e/e5/6747724f52c037b8bbe7c2079501181ad81969b7a30ce2b6f5d01a7f0346/python-chess-0.23.11.tar.gz (140kB)
    100% |████████████████████████████████| 143kB 1.5MB/s 
Installing collected packages: python-chess
  Running setup.py install for python-chess ... done
Successfully installed python-chess-0.23.11
[roland@portable Linux]$ LC_ALL=C sh xlucas.sh
x86_64
Traceback (most recent call last):
  File "./Lucas.py", line 44, in <module>
    import Code.Init
  File "./Code/Init.py", line 5, in <module>
    from Code import Procesador
  File "./Code/Procesador.py", line 30, in <module>
    from Code import GestorRoutes
  File "./Code/GestorRoutes.py", line 11, in <module>
    from Code import LibChess
  File "./Code/LibChess.py", line 4, in <module>
    import chess
ImportError: No module named chess
[roland@portable Linux]$ 
```

**Comment by xaizek** [comment]
Try using `pip2` instead of `pip`. The latter might be resolved to `pip3` and install the package only for Python3. Or just check that output of `sudo pip --version` mentions `python 2.7`.

**Comment by rchastain** [comment]
Great! It works with `pip2`. Now I can start Lucas Chess. Thank you for your help.
