### ISSUE TITLE
Lucaschess not running after upgrading to ubuntu 20.04

### ISSUE THREAD

**Issue by Arunachala-Ramana** [lukasmonk/lucaschess#129]
Recently upgraded my system and tried installing lucaschess again. 

I seem to get the error when i run the command `bash xmk_linux.sh`. This is the error

```
lc.c: In function ‘pgn2pv’:
lc.c:169:13: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
  169 |             if( promotion ) sprintf(pv, "%s%c", pv, promotion);
      |             ^~
lc.c: In function ‘getMove’:
lc.c:211:5: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
  211 |     if( move.promotion ) sprintf(pv, "%s%c", pv, tolower(NAMEPZ[move.promotion]));
      |     ^~
lc.c: In function ‘getMoveEx’:
lc.c:255:5: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
  255 |     sprintf(info, "%s%c%c%c", info, promotion, castle, en_passant);
      |     ^~~~~~~
lc.c: In function ‘toSan’:
lc.c:288:13: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
  288 |             sprintf(sanMove, "%s=%c", sanMove, toupper(NAMEPZ[move.promotion]));
      |             ^~~~~~~
lc.c:306:9: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
  306 |         if( is_amb_ah ) sprintf(sanMove,"%s%c", sanMove, POS_AH[move.from][0]);
      |         ^~
lc.c:307:9: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
  307 |         if( is_amb_18 ) sprintf(sanMove,"%s%c", sanMove, POS_AH[move.from][1]);
      |         ^~
lc.c:308:9: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
  308 |         if(move.capture) sprintf(sanMove,"%sx", sanMove);
      |         ^~
lc.c:309:9: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
  309 |         sprintf(sanMove,"%s%s", sanMove, POS_AH[move.to]);
      |         ^~~~~~~
lc.c:316:13: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
  316 |             sprintf(sanMove,"%s#", sanMove);
      |             ^~~~~~~
lc.c:318:13: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
  318 |             sprintf(sanMove,"%s+", sanMove);
      |             ^~~~~~~
board.c: In function ‘board_fen’:
board.c:250:5: warning: passing argument 1 to restrict-qualified parameter aliases with argument 3 [-Wrestrict]
  250 |     sprintf(fen, "%s %d %d", fen, board.fifty, board.fullmove);
      |     ^~~~~~~
util.c: In function ‘get_ms’:
util.c:53:5: warning: ‘ftime’ is deprecated [-Wdeprecated-declarations]
   53 |     ftime(&buffer);
      |     ^~~~~
In file included from util.c:2:
/usr/include/x86_64-linux-gnu/sys/timeb.h:39:12: note: declared here
   39 | extern int ftime (struct timeb *__timebuf)
```

Not sure what i have done wrong and it would be nice if somebody can help.

**Comment by xaizek** [comment]
Those are warnings. The code isn't entirely correct, but will probably work.

**Comment by Arunachala-Ramana** [comment]
Emm.  Let me check

**Comment by Arunachala-Ramana** [comment]
See if there are any errors

```
chandru1@chandru-hp:~/lucaschess/LCEngine$ bash xcython_linux.sh
rm: cannot remove 'LCEngine4.so': No such file or directory
running build_ext
building 'LCEngine4' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-1x6jhf/python2.7-2.7.18~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c LCEngine4.c -o build/temp.linux-x86_64-2.7/LCEngine4.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-1x6jhf/python2.7-2.7.18~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-1x6jhf/python2.7-2.7.18~rc1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC build/temp.linux-x86_64-2.7/LCEngine4.o -lirina -o /home/chandru1/lucaschess/LCEngine/LCEngine4.so
x86_64
chandru1@chandru-hp:~/lucaschess/LCEngine$ cd ..
chandru1@chandru-hp:~/lucaschess$ cd Linux
chandru1@chandru-hp:~/lucaschess/Linux$ bash xlucas.sh
x86_64
Traceback (most recent call last):
  File "./Lucas.py", line 44, in <module>
    import Code.Init
  File "./Code/Init.py", line 5, in <module>
    from Code import Procesador
  File "./Code/Procesador.py", line 10, in <module>
    from Code import XGestorMotor
  File "./Code/XGestorMotor.py", line 6, in <module>
    from Code import XMotor
  File "./Code/XMotor.py", line 7, in <module>
    from PyQt4 import QtCore
ImportError: No module named PyQt4

```

I am not able to run. Did i miss any dependency like Qt4, if yes please let me know the commands for installing them, as qt5 only seems to be available. 

Thanks a lot.

**Comment by xaizek** [comment]
Ubuntu 20.04 dropped support for Qt4. Packages from older releases might work or you can build it yourself (in both cases you also need PyQt and maybe some other old versions), look for articles on using Qt4 in Ubuntu 20.04.

You  can also try https://github.com/lukasmonk/lucaschessR (not sure it works on Linux yet). Or use Windows version via Wine.

**Comment by Arunachala-Ramana** [comment]
Yeah will try searching and get back.

**Comment by Arunachala-Ramana** [comment]
Emm. Installed Pyqt but now error shows up as no module called pyaudio. I did install python3-pyaudio. 

```

chandru1@chandru-hp:~/lucaschess/Linux$ bash xlucas.sh
x86_64
Traceback (most recent call last):
  File "./Lucas.py", line 44, in <module>
    import Code.Init
  File "./Code/Init.py", line 5, in <module>
    from Code import Procesador
  File "./Code/Procesador.py", line 55, in <module>
    from Code.QT import PantallaSonido
  File "./Code/QT/PantallaSonido.py", line 17, in <module>
    from Code import Sonido
  File "./Code/Sonido.py", line 7, in <module>
    import pyaudio
ImportError: No module named pyaudio
```
```
chandru1@chandru-hp:~/lucaschess/Linux$ sudo apt-get install python3-pyaudio
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pyaudio is already the newest version (0.2.11-1.1build1).
```

Anything i did wrong?

**Comment by xaizek** [comment]
> `python3-pyaudio`

LucasChess uses python2.

**Comment by Arunachala-Ramana** [comment]
Emm. So what should i do now to rectify? I am not aware

**Comment by Arunachala-Ramana** [comment]
Got it working. Posted this question here: https://askubuntu.com/questions/1265294/pyqt4-on-ubuntu-20-04-install and some people were very kind to help :+1:  Thanks to you as well for the help.
