### ISSUE TITLE
Change UsrData folder doesn't work both on Windows and Linux.

### ISSUE THREAD

**Issue by JulyMorning** [lukasmonk/lucaschess#14]
Version 9.08
Traceback (most recent call last):
  File "Code\QT\WBase.pyo", line 254, in procesarAccion
  File "Code\Procesador.pyo", line 404, in procesarAccion
  File "Code\Procesador.pyo", line 472, in opciones
  File "Code\Procesador.pyo", line 519, in folder_change
AttributeError: Configuracion instance has no attribute 'changeFolder'

**Comment by lukasmonk** [comment]
Fixed, thank you very much
