### ISSUE TITLE
ValueError: PyCapsule_GetPointer called with invalid PyCapsule object

### ISSUE THREAD

**Issue by seb321** [lukasmonk/lucaschess#3]
Hi,
(Sorry English isn't my native language.)

I'm trying to run lucas chess, but i'm getting error:

seb321@seb321-K54HR:~/lucaschess$ ./Lucas.py 
Traceback (most recent call last):
  File "./Lucas.py", line 41, in <module>
    import Code.Init
  File "/home/seb321/lucaschess/Code/Init.py", line 12, in <module>
    import Code.Procesador as Procesador
  File "/home/seb321/lucaschess/Code/Procesador.py", line 22, in <module>
    import Code.GestorSolo as GestorSolo
  File "/home/seb321/lucaschess/Code/GestorSolo.py", line 12, in <module>
    import Code.Voice as Voice
  File "/home/seb321/lucaschess/Code/Voice.py", line 10, in <module>
    from pocketsphinx import Decoder
  File "sphinxbase.pxd", line 150, in init pocketsphinx (pocketsphinx.c:7935)
ValueError: PyCapsule_GetPointer called with invalid PyCapsule object

Ubuntu 14.04 64 bit

What i'm doing wrong?
Help!

**Comment by seb321** [comment]
*Ubuntu 14.04 64 bit

**Comment by lukasmonk** [comment]
Hi

You could try to edit file Code/Voice.py, and the 10 line to change:

FROM:
from pocketsphing import Decoder

TO:
class Decoder:
    pass


Cheers
Lucas

From:  seb321
Date:  2015-08-29 23:06
Subject:  Re: [lucaschess] ValueError: PyCapsule_GetPointer called with invalid PyCapsule object (#3)
 
*Ubuntu 14.04 64 bit

**Comment by seb321** [comment]
Thanks, it's working.
