### ISSUE TITLE
Exception in Play current position

### ISSUE THREAD

**Issue by tico-tico** [lukasmonk/lucaschess#31]
`Play` -> `Play against an engine of your choice`. Select **Monkey** as an opponent. Make several moves. `Utilities` -> `Play current position`. Select **Monkey** too, press *Accept*.

```
Traceback (most recent call last):
  File "lucas.py", line 58, in <module>
  File ".\Code\Init.py", line 27, in init
    resp = Gui.lanzaGUI(mainProcesador)
  File "Code\QT\Gui.pyo", line 116, in lanzaGUI
    
  File "Code\Procesador.pyo", line 160, in iniciarGUI
    
  File "Code\Procesador.pyo", line 808, in juegaExterno
    
  File "Code\GestorSolo.pyo", line 178, in inicio
    
  File "Code\GestorSolo.pyo", line 860, in cambioRival
    
  File "Code\Configuracion.pyo", line 791, in escVariables
    
  File ".\Code\Util.py", line 894, in __setitem__
    dato = base64.encodestring(cPickle.dumps(obj))
  File "copy_reg.pyo", line 71, in _reduce_ex
TypeError: the sip.wrapper type cannot be instantiated or sub-classed
```

**Comment by lukasmonk** [comment]
Fixed, I hope. Thank you very much.

**Comment by tico-tico** [comment]
Fixed, thanks!
