### ISSUE TITLE
Exception when tried Change opponent

### ISSUE THREAD

**Issue by tico-tico** [lukasmonk/lucaschess#32]
`Play` -> `Play against an engine of your choice`. Select **Monkey** as an opponent. Start game, then `Config` -> `Change opponent`. Choose **Donkey**, click `Accept`.

```
Traceback (most recent call last):
  File ".\Code\QT\WBase.py", line 259, in procesarAccion
    self.gestor.procesarAccion(self.sender().clave)
  File ".\Code\GestorEntMaq.py", line 324, in procesarAccion
    self.cambioRival()
  File ".\Code\GestorEntMaq.py", line 1030, in cambioRival
    Util.guardaDIC(dic, self.configuracion.ficheroEntMaquina)
  File ".\Code\Util.py", line 42, in guardaDIC
    q.write(base64.encodestring(cPickle.dumps(dic)))
  File "copy_reg.pyo", line 71, in _reduce_ex
TypeError: the sip.wrapper type cannot be instantiated or sub-classed
```

**Comment by tico-tico** [comment]
**Adjourn** exception:

```
Traceback (most recent call last):
  File ".\Code\QT\WBase.py", line 259, in procesarAccion
    self.gestor.procesarAccion(self.sender().clave)
  File ".\Code\GestorEntMaq.py", line 348, in procesarAccion
    self.aplazar()
  File ".\Code\GestorEntMaq.py", line 390, in aplazar
    self.configuracion.graba(self.genAplazamiento())
  File ".\Code\Configuracion.py", line 522, in graba
    dic["APLAZAMIENTO"] = Util.dic2txt(aplazamiento)
  File ".\Code\Util.py", line 108, in dic2txt
    return base64.encodestring(cPickle.dumps(dic)).replace("\n", "|")
  File "copy_reg.pyo", line 71, in _reduce_ex
TypeError: the sip.wrapper type cannot be instantiated or sub-classed
```

**Comment by lukasmonk** [comment]
Fixed.
Thank you very much.

**Comment by tico-tico** [comment]
Thanks, no exception any more. But if I switch from **Monkey** to **Rodent** I still can see *irina.exe* in the running processes. It's not a big deal if you use *irina*, but can be waste of RAM if you use an engine with a big hash size. So i think that previous engine's executable should be closed,

**Comment by lukasmonk** [comment]
Fixed this new bug detected.
Thank you very much.

**Comment by tico-tico** [comment]
It's OK now. Thanks!
