### ISSUE TITLE
Run error libirina.so not found

### ISSUE THREAD

**Issue by jianlianggao** [lukasmonk/lucaschess#48]
Hi,

I followed the installation in LinuxInstallation.md and ran: python Lucas.py 
Traceback (most recent call last):
  File "Lucas.py", line 61, in <module>
    import Code.Init
  File "./Code/Init.py", line 5, in <module>
    from Code import Procesador
  File "./Code/Procesador.py", line 6, in <module>
    from Code import Routes
  File "./Code/Routes.py", line 5, in <module>
    from Code import Partida
  File "./Code/Partida.py", line 2, in <module>
    from Code import ControlPosicion
  File "./Code/ControlPosicion.py", line 1, in <module>
    import LCEngine
ImportError: libirina.so: cannot open shared object file: No such file or directory

Any idea?

Thanks,
Jianliang

**Comment by lukasmonk** [comment]
There is necessary to create libirina.so:
https://github.com/lukasmonk/lucaschess/blob/master/LCEngine/xcython_linux.sh

**Comment by jianlianggao** [comment]
Thank you very much, I have the issue sorted.
