### ISSUE TITLE
No black moves for opening repertoire on Linux

### ISSUE THREAD

**Issue by antoyo** [lukasmonk/lucaschess#73]
Hi.
This issue only exists in the Linux version; the Windows version works fine.
For any feature involving opening repertoire, there are no moves for black.
For instance, when I create a custom repertoire, I can only enter white moves.
Same for opening lines.
Thanks to fix this issue.

**Comment by lukasmonk** [comment]
Are you trying the binary version to Linux 64 bits?

https://drive.google.com/open?id=1joGQWTmJMVfYGyLLdpayo5KHcTfqxi1-

**Comment by antoyo** [comment]
I was trying the git version, but same problem with this.

**Comment by lukasmonk** [comment]
Is there some data in bug.log file (in install folder)?
What version have you, 32bits or 64 bits?
What Linux distibution?

**Comment by lukasmonk** [comment]
Sorry, I have no idea. (With the binary distribution in a Cinnamon-64 bits, I have no problem)
With the binary distribution, first remove bug.log, then you could try renaming UsrData folder to UsrData0, by example and then exec xlucas.sh, open Opening Lines distribution.
If fail, in this folder could you exec chmod -R 777 * to assign all permisions, then ./xlucas.sh
And show again the new bug.log file.

**Comment by antoyo** [comment]
The only error I got was the following, when I double-clicked on the new opening:
```
Traceback (most recent call last):
  File "Code/QT/Grid.py", line 345, in mouseDoubleClickEvent
  File "Code/QT/PantallaAperturas.py", line 754, in gridDobleClick
  File "Code/QT/PantallaAperturas.py", line 810, in editar
  File "Code/Variantes.py", line 16, in editaVariante
  File "Code/GestorVariantes.py", line 31, in inicio
AttributeError: UnPGN instance has no attribute 'partida'
```
I'll take a look at the code to try to find what's the issue.

**Comment by lukasmonk** [comment]
You could insert in line 73 of PGNreader.py:

    import sys
    sys.stderr.write("\n[%s]\n[%s]\n" %(fen,txt))

To know which is the text sended.

**Comment by lukasmonk** [comment]
File: Code/GestorVariantes.py
Method: def mueveHumano    line:184

**Comment by antoyo** [comment]
First test I did is to print `jg` and play the moves d4, c4 and Nc3 (without black moves because I can't) and here's the output:
```
d2 d4 : rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
c2 c4 : rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
b1 c3 : rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
```
If you find anything abnormal in this, please tell me.
I'll try other tests.

**Comment by lukasmonk** [comment]
The poblem can be detected (perhaps) in line 73 of PGNreader.py:

To know which is the text sended and the fen..

**Comment by lukasmonk** [comment]
In file: Code/GestorVariantes.py
Method: def mueveHumano 
from line:184
the question is, when it is produced a bug, in which line.
bug.log, is indicating this probably.

**Comment by antoyo** [comment]
The PGN reader looks fine.
For instance, with the following PGN:
```
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]
[ECO "C50"]

1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6  *
```
I get the following `fen` and `txt`:
```
rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
1. e4 e5 2. Nf3 Nc6 3. Bc4 Nf6  *
```

**Comment by lukasmonk** [comment]
The problem is not reading a pgn, the problem is that it is trying to read an automatic pgn, created by the program, and which for any reason is incorrect.

**Comment by antoyo** [comment]
I'm not sure I explained the problem correctly, so I'll give you screenshots of this issue in another scenario.
If I go in Tool → Create your own game, I can only play the white pieces, even multiple times in a row.
![mouseblackpiece](https://user-images.githubusercontent.com/584972/45268930-7d75f300-b452-11e8-8894-8134d40a7342.png)
As you can see in the previous image, the mouse cursor indicates that I cannot move a black piece.
![mousewhitepiece](https://user-images.githubusercontent.com/584972/45268931-7d75f300-b452-11e8-9863-7f15762d49f0.png)
The cursor here indicates that I can move a white piece.

So, it seems to me that it is more of a GUI problem.

**Comment by lukasmonk** [comment]
Yes it is a GUI problem, playing in a context that I can´t replicate because all other contests (windows-Linux Cinnamon64) that I could control works well.
For this reason, I need information, and the next could be a good way:

You could insert in line 73 of PGNreader.py:

    import sys
    sys.stderr.write("\n[%s]\n[%s]\n" %(fen,txt))

To know which is the text sended to bug.log.

**Comment by antoyo** [comment]
So, for some reasons, `Tablero.activaColor` is always called with `siBlancas=True`.
Does that look normal?

**Comment by lukasmonk** [comment]
No.

Create your own game is controlled in file GestorSolo.py

The loop to read moves is in line 324: def siguienteJugada   (nextMove in english)

The side is controlled in line 333: siBlancas = ...    (is White or not)

The move done by user is checked in line 365: 
def mueveHumano  (humanMove in english)

Something in this method is working bad, because of this the move is not added to variable that controls the game (self.partida)

It is needed to test if all lines are executed, and in why is not added the move, at end why the line 393 is not executed ?

**Comment by antoyo** [comment]
When I print `jg` and play multiple moves, I get the following:
```
e2 e4 : rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
d2 d4 : rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
```
Does the FEN next to the move indicate the current position?
If yes, it looks like the move is not actually registered in the game state and that seems to be the case, because I cannot play `e5` after I played `e4`, for instance.

**Comment by lukasmonk** [comment]
Could be.
But a way to know it is to follow that I have indicated  in the previous message.

**Comment by antoyo** [comment]
All of `mueveHumano` (except the block `if self.siJuegaMotor and not self.partida.siEstaTerminada():`) is executed and `self.partida.append_jg` is indeed called.

**Comment by lukasmonk** [comment]
Then jg variable is incorrect.
You could try to recompile LCEngineV1.so and irina.so, from folder LCEngine, subfolder irina.

**Comment by antoyo** [comment]
Recompiling seemed to have fixed the issue.
But I just noticed many other bugs like I cannot open the personal opening guide and even a segfault.
Are you able to open the personal opening guide on your side, in the Linux version?

**Comment by lukasmonk** [comment]
It works in cinnamon-64 without problems.

File "Code/ControlPosicion.py", line 297, in pgnSP
This is in relation to LCEngine.

**Comment by antoyo** [comment]
I understand that it works with the cinnamon desktop environement, but which distribution do you use?

**Comment by lukasmonk** [comment]
Linux Mint 18.1 - Cinnamon 64 bits

**Comment by antoyo** [comment]
I've tried with the same distribution and it indeed works.

**Comment by lukasmonk** [comment]
It seems that for some reason LCEngineV1.so or libirina.so, are not working properly in ArchLinux.
